// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: readings.proto

package storiespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestSaveReading ...
type RequestSaveReading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChapterID string  `protobuf:"bytes,1,opt,name=ChapterID,proto3" json:"ChapterID,omitempty"`
	Percent   float32 `protobuf:"fixed32,2,opt,name=Percent,proto3" json:"Percent,omitempty"`
}

func (x *RequestSaveReading) Reset() {
	*x = RequestSaveReading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_readings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSaveReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSaveReading) ProtoMessage() {}

func (x *RequestSaveReading) ProtoReflect() protoreflect.Message {
	mi := &file_readings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSaveReading.ProtoReflect.Descriptor instead.
func (*RequestSaveReading) Descriptor() ([]byte, []int) {
	return file_readings_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSaveReading) GetChapterID() string {
	if x != nil {
		return x.ChapterID
	}
	return ""
}

func (x *RequestSaveReading) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

var File_readings_proto protoreflect.FileDescriptor

var file_readings_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x12, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x72, 0x6e, 0x65, 0x73, 0x74, 0x6f, 0x47, 0x46, 0x2f,
	0x62, 0x6f, 0x75, 0x6b, 0x6b, 0x65, 0x72, 0x2d, 0x6e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x32, 0x2f,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_readings_proto_rawDescOnce sync.Once
	file_readings_proto_rawDescData = file_readings_proto_rawDesc
)

func file_readings_proto_rawDescGZIP() []byte {
	file_readings_proto_rawDescOnce.Do(func() {
		file_readings_proto_rawDescData = protoimpl.X.CompressGZIP(file_readings_proto_rawDescData)
	})
	return file_readings_proto_rawDescData
}

var file_readings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_readings_proto_goTypes = []interface{}{
	(*RequestSaveReading)(nil), // 0: stories.RequestSaveReading
}
var file_readings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_readings_proto_init() }
func file_readings_proto_init() {
	if File_readings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_readings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSaveReading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_readings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_readings_proto_goTypes,
		DependencyIndexes: file_readings_proto_depIdxs,
		MessageInfos:      file_readings_proto_msgTypes,
	}.Build()
	File_readings_proto = out.File
	file_readings_proto_rawDesc = nil
	file_readings_proto_goTypes = nil
	file_readings_proto_depIdxs = nil
}
