// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: stories.proto

package storiespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusType int32

const (
	StatusType_ST_IGNORE StatusType = 0
	StatusType_ST_DRAFT  StatusType = 1
	StatusType_ST_PUBLIC StatusType = 2
)

// Enum value maps for StatusType.
var (
	StatusType_name = map[int32]string{
		0: "ST_IGNORE",
		1: "ST_DRAFT",
		2: "ST_PUBLIC",
	}
	StatusType_value = map[string]int32{
		"ST_IGNORE": 0,
		"ST_DRAFT":  1,
		"ST_PUBLIC": 2,
	}
)

func (x StatusType) Enum() *StatusType {
	p := new(StatusType)
	*p = x
	return p
}

func (x StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[0].Descriptor()
}

func (StatusType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[0]
}

func (x StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusType.Descriptor instead.
func (StatusType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{0}
}

// ReactionType ...
type ReactionType int32

const (
	ReactionType_RT_IGNORE ReactionType = 0
	ReactionType_RT_LIKE   ReactionType = 1
	ReactionType_RT_VIEW   ReactionType = 2
)

// Enum value maps for ReactionType.
var (
	ReactionType_name = map[int32]string{
		0: "RT_IGNORE",
		1: "RT_LIKE",
		2: "RT_VIEW",
	}
	ReactionType_value = map[string]int32{
		"RT_IGNORE": 0,
		"RT_LIKE":   1,
		"RT_VIEW":   2,
	}
)

func (x ReactionType) Enum() *ReactionType {
	p := new(ReactionType)
	*p = x
	return p
}

func (x ReactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[1].Descriptor()
}

func (ReactionType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[1]
}

func (x ReactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReactionType.Descriptor instead.
func (ReactionType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{1}
}

// AudienceType ...
type AudienceType int32

const (
	AudienceType_AT_IGNORE AudienceType = 0
	// AT_ALL all
	AudienceType_AT_ALL AudienceType = 1
	// AT_YOUNG 13-18 years
	AudienceType_AT_YOUNG AudienceType = 2
	// AT_ADULT +18 years
	AudienceType_AT_ADULT AudienceType = 3
)

// Enum value maps for AudienceType.
var (
	AudienceType_name = map[int32]string{
		0: "AT_IGNORE",
		1: "AT_ALL",
		2: "AT_YOUNG",
		3: "AT_ADULT",
	}
	AudienceType_value = map[string]int32{
		"AT_IGNORE": 0,
		"AT_ALL":    1,
		"AT_YOUNG":  2,
		"AT_ADULT":  3,
	}
)

func (x AudienceType) Enum() *AudienceType {
	p := new(AudienceType)
	*p = x
	return p
}

func (x AudienceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudienceType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[2].Descriptor()
}

func (AudienceType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[2]
}

func (x AudienceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudienceType.Descriptor instead.
func (AudienceType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{2}
}

// CopyrigthType ...
type CopyrigthType int32

const (
	CopyrigthType_CRT_IGNORE                              CopyrigthType = 0
	CopyrigthType_CRT_ALL_RIGHTS_RESERVED                 CopyrigthType = 1
	CopyrigthType_CRT_PUBLIC_DOMAIN                       CopyrigthType = 2
	CopyrigthType_CRT_CREATIVE_COMMONS_ATTRIBUTION        CopyrigthType = 3
	CopyrigthType_CRT_CC_ATTRIB_NON_COMMERCIAL            CopyrigthType = 4
	CopyrigthType_CRT_CC_ATTRIB_NON_COMMERCIAL_NO_DERIVS  CopyrigthType = 5
	CopyrigthType_CRT_CC_ATTRIB_NON_COMMERCIAL_SHAREALIKE CopyrigthType = 6
	CopyrigthType_CRT_CC_ATTRIBUTION_SHAREALIKE           CopyrigthType = 7
	CopyrigthType_CRT_CC_ATTRIBUTION_NO_DERIVS            CopyrigthType = 8
)

// Enum value maps for CopyrigthType.
var (
	CopyrigthType_name = map[int32]string{
		0: "CRT_IGNORE",
		1: "CRT_ALL_RIGHTS_RESERVED",
		2: "CRT_PUBLIC_DOMAIN",
		3: "CRT_CREATIVE_COMMONS_ATTRIBUTION",
		4: "CRT_CC_ATTRIB_NON_COMMERCIAL",
		5: "CRT_CC_ATTRIB_NON_COMMERCIAL_NO_DERIVS",
		6: "CRT_CC_ATTRIB_NON_COMMERCIAL_SHAREALIKE",
		7: "CRT_CC_ATTRIBUTION_SHAREALIKE",
		8: "CRT_CC_ATTRIBUTION_NO_DERIVS",
	}
	CopyrigthType_value = map[string]int32{
		"CRT_IGNORE":                              0,
		"CRT_ALL_RIGHTS_RESERVED":                 1,
		"CRT_PUBLIC_DOMAIN":                       2,
		"CRT_CREATIVE_COMMONS_ATTRIBUTION":        3,
		"CRT_CC_ATTRIB_NON_COMMERCIAL":            4,
		"CRT_CC_ATTRIB_NON_COMMERCIAL_NO_DERIVS":  5,
		"CRT_CC_ATTRIB_NON_COMMERCIAL_SHAREALIKE": 6,
		"CRT_CC_ATTRIBUTION_SHAREALIKE":           7,
		"CRT_CC_ATTRIBUTION_NO_DERIVS":            8,
	}
)

func (x CopyrigthType) Enum() *CopyrigthType {
	p := new(CopyrigthType)
	*p = x
	return p
}

func (x CopyrigthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyrigthType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[3].Descriptor()
}

func (CopyrigthType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[3]
}

func (x CopyrigthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyrigthType.Descriptor instead.
func (CopyrigthType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{3}
}

// ClasificationType ...
type ClasificationType int32

const (
	ClasificationType_CT_IGNORE ClasificationType = 0
	ClasificationType_CT_ALl    ClasificationType = 1
)

// Enum value maps for ClasificationType.
var (
	ClasificationType_name = map[int32]string{
		0: "CT_IGNORE",
		1: "CT_ALl",
	}
	ClasificationType_value = map[string]int32{
		"CT_IGNORE": 0,
		"CT_ALl":    1,
	}
)

func (x ClasificationType) Enum() *ClasificationType {
	p := new(ClasificationType)
	*p = x
	return p
}

func (x ClasificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClasificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[4].Descriptor()
}

func (ClasificationType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[4]
}

func (x ClasificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClasificationType.Descriptor instead.
func (ClasificationType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{4}
}

// CommentModerationType ...
type CommentModerationType int32

const (
	CommentModerationType_CMT_IGNORE CommentModerationType = 0
	CommentModerationType_CMT_NONE   CommentModerationType = 1
	CommentModerationType_CMT_MANUAL CommentModerationType = 2
	CommentModerationType_CMT_KATHE  CommentModerationType = 3
)

// Enum value maps for CommentModerationType.
var (
	CommentModerationType_name = map[int32]string{
		0: "CMT_IGNORE",
		1: "CMT_NONE",
		2: "CMT_MANUAL",
		3: "CMT_KATHE",
	}
	CommentModerationType_value = map[string]int32{
		"CMT_IGNORE": 0,
		"CMT_NONE":   1,
		"CMT_MANUAL": 2,
		"CMT_KATHE":  3,
	}
)

func (x CommentModerationType) Enum() *CommentModerationType {
	p := new(CommentModerationType)
	*p = x
	return p
}

func (x CommentModerationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentModerationType) Descriptor() protoreflect.EnumDescriptor {
	return file_stories_proto_enumTypes[5].Descriptor()
}

func (CommentModerationType) Type() protoreflect.EnumType {
	return &file_stories_proto_enumTypes[5]
}

func (x CommentModerationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentModerationType.Descriptor instead.
func (CommentModerationType) EnumDescriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{5}
}

// RequestWriteStory ...
type RequestWriteStory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title             string                `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author            string                `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	IsOriginal        bool                  `protobuf:"varint,4,opt,name=IsOriginal,proto3" json:"IsOriginal,omitempty"`
	Tags              []string              `protobuf:"bytes,5,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CategoryID        string                `protobuf:"bytes,6,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	LanguageID        string                `protobuf:"bytes,7,opt,name=LanguageID,proto3" json:"LanguageID,omitempty"`
	TokenCover        string                `protobuf:"bytes,8,opt,name=TokenCover,proto3" json:"TokenCover,omitempty"`
	Status            StatusType            `protobuf:"varint,9,opt,name=Status,proto3,enum=stories.StatusType" json:"Status,omitempty"`
	Characters        []string              `protobuf:"bytes,12,rep,name=Characters,proto3" json:"Characters,omitempty"`
	Audience          AudienceType          `protobuf:"varint,13,opt,name=Audience,proto3,enum=stories.AudienceType" json:"Audience,omitempty"`
	Copyright         CopyrigthType         `protobuf:"varint,14,opt,name=Copyright,proto3,enum=stories.CopyrigthType" json:"Copyright,omitempty"`
	Clasification     ClasificationType     `protobuf:"varint,15,opt,name=Clasification,proto3,enum=stories.ClasificationType" json:"Clasification,omitempty"`
	CommentModeration CommentModerationType `protobuf:"varint,16,opt,name=CommentModeration,proto3,enum=stories.CommentModerationType" json:"CommentModeration,omitempty"`
}

func (x *RequestWriteStory) Reset() {
	*x = RequestWriteStory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWriteStory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWriteStory) ProtoMessage() {}

func (x *RequestWriteStory) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWriteStory.ProtoReflect.Descriptor instead.
func (*RequestWriteStory) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWriteStory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RequestWriteStory) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *RequestWriteStory) GetIsOriginal() bool {
	if x != nil {
		return x.IsOriginal
	}
	return false
}

func (x *RequestWriteStory) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RequestWriteStory) GetCategoryID() string {
	if x != nil {
		return x.CategoryID
	}
	return ""
}

func (x *RequestWriteStory) GetLanguageID() string {
	if x != nil {
		return x.LanguageID
	}
	return ""
}

func (x *RequestWriteStory) GetTokenCover() string {
	if x != nil {
		return x.TokenCover
	}
	return ""
}

func (x *RequestWriteStory) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_ST_IGNORE
}

func (x *RequestWriteStory) GetCharacters() []string {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *RequestWriteStory) GetAudience() AudienceType {
	if x != nil {
		return x.Audience
	}
	return AudienceType_AT_IGNORE
}

func (x *RequestWriteStory) GetCopyright() CopyrigthType {
	if x != nil {
		return x.Copyright
	}
	return CopyrigthType_CRT_IGNORE
}

func (x *RequestWriteStory) GetClasification() ClasificationType {
	if x != nil {
		return x.Clasification
	}
	return ClasificationType_CT_IGNORE
}

func (x *RequestWriteStory) GetCommentModeration() CommentModerationType {
	if x != nil {
		return x.CommentModeration
	}
	return CommentModerationType_CMT_IGNORE
}

// ResponseID ...
type ResponseID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ResponseID) Reset() {
	*x = ResponseID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseID) ProtoMessage() {}

func (x *ResponseID) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseID.ProtoReflect.Descriptor instead.
func (*ResponseID) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// CategoryInfo ...
type CategoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Transkey string `protobuf:"bytes,3,opt,name=Transkey,proto3" json:"Transkey,omitempty"`
}

func (x *CategoryInfo) Reset() {
	*x = CategoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfo) ProtoMessage() {}

func (x *CategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfo.ProtoReflect.Descriptor instead.
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfo) GetTranskey() string {
	if x != nil {
		return x.Transkey
	}
	return ""
}

// LanguageInfo ...
type LanguageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Transkey string `protobuf:"bytes,3,opt,name=Transkey,proto3" json:"Transkey,omitempty"`
}

func (x *LanguageInfo) Reset() {
	*x = LanguageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageInfo) ProtoMessage() {}

func (x *LanguageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageInfo.ProtoReflect.Descriptor instead.
func (*LanguageInfo) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{3}
}

func (x *LanguageInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *LanguageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguageInfo) GetTranskey() string {
	if x != nil {
		return x.Transkey
	}
	return ""
}

// UserInfo ...
type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar   string `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// TotalReactionInfo ...
type TotalReactionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  ReactionType `protobuf:"varint,1,opt,name=Type,proto3,enum=stories.ReactionType" json:"Type,omitempty"`
	Total int64        `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *TotalReactionInfo) Reset() {
	*x = TotalReactionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalReactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalReactionInfo) ProtoMessage() {}

func (x *TotalReactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalReactionInfo.ProtoReflect.Descriptor instead.
func (*TotalReactionInfo) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{5}
}

func (x *TotalReactionInfo) GetType() ReactionType {
	if x != nil {
		return x.Type
	}
	return ReactionType_RT_IGNORE
}

func (x *TotalReactionInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ChapterPosition ...
type ChapterPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position int32  `protobuf:"varint,2,opt,name=Position,proto3" json:"Position,omitempty"`
}

func (x *ChapterPosition) Reset() {
	*x = ChapterPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stories_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChapterPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterPosition) ProtoMessage() {}

func (x *ChapterPosition) ProtoReflect() protoreflect.Message {
	mi := &file_stories_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterPosition.ProtoReflect.Descriptor instead.
func (*ChapterPosition) Descriptor() ([]byte, []int) {
	return file_stories_proto_rawDescGZIP(), []int{6}
}

func (x *ChapterPosition) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ChapterPosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_stories_proto protoreflect.FileDescriptor

var file_stories_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x9b, 0x04, 0x0a, 0x11, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x49, 0x73, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x44, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x12, 0x31, 0x0a,
	0x08, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x34, 0x0a, 0x09, 0x43, 0x6f, 0x70, 0x79, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x70, 0x79, 0x72, 0x69, 0x67, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x43, 0x6f, 0x70,
	0x79, 0x72, 0x69, 0x67, 0x68, 0x74, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x43, 0x6c, 0x61, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6b, 0x65, 0x79, 0x22, 0x4e, 0x0a, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6b, 0x65, 0x79, 0x22, 0x62, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x54, 0x0a, 0x11, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3d,
	0x0a, 0x0f, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x38, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x54, 0x5f, 0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54,
	0x5f, 0x44, 0x52, 0x41, 0x46, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x54, 0x5f, 0x50,
	0x55, 0x42, 0x4c, 0x49, 0x43, 0x10, 0x02, 0x2a, 0x37, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x54, 0x5f, 0x49, 0x47,
	0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x54, 0x5f, 0x4c, 0x49, 0x4b,
	0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x54, 0x5f, 0x56, 0x49, 0x45, 0x57, 0x10, 0x02,
	0x2a, 0x45, 0x0a, 0x0c, 0x41, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x54, 0x5f, 0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41,
	0x54, 0x5f, 0x59, 0x4f, 0x55, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x54, 0x5f,
	0x41, 0x44, 0x55, 0x4c, 0x54, 0x10, 0x03, 0x2a, 0xb9, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x70, 0x79,
	0x72, 0x69, 0x67, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x52, 0x54,
	0x5f, 0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x52, 0x54,
	0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x52, 0x54, 0x5f, 0x50, 0x55,
	0x42, 0x4c, 0x49, 0x43, 0x5f, 0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x24, 0x0a,
	0x20, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x49, 0x56, 0x45, 0x5f, 0x43, 0x4f,
	0x4d, 0x4d, 0x4f, 0x4e, 0x53, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x03, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x43, 0x5f, 0x41, 0x54,
	0x54, 0x52, 0x49, 0x42, 0x5f, 0x4e, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x52, 0x43,
	0x49, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x2a, 0x0a, 0x26, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x43, 0x5f,
	0x41, 0x54, 0x54, 0x52, 0x49, 0x42, 0x5f, 0x4e, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45,
	0x52, 0x43, 0x49, 0x41, 0x4c, 0x5f, 0x4e, 0x4f, 0x5f, 0x44, 0x45, 0x52, 0x49, 0x56, 0x53, 0x10,
	0x05, 0x12, 0x2b, 0x0a, 0x27, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x43, 0x5f, 0x41, 0x54, 0x54, 0x52,
	0x49, 0x42, 0x5f, 0x4e, 0x4f, 0x4e, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x52, 0x43, 0x49, 0x41,
	0x4c, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x45, 0x41, 0x4c, 0x49, 0x4b, 0x45, 0x10, 0x06, 0x12, 0x21,
	0x0a, 0x1d, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x43, 0x5f, 0x41, 0x54, 0x54, 0x52, 0x49, 0x42, 0x55,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x48, 0x41, 0x52, 0x45, 0x41, 0x4c, 0x49, 0x4b, 0x45, 0x10,
	0x07, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x52, 0x54, 0x5f, 0x43, 0x43, 0x5f, 0x41, 0x54, 0x54, 0x52,
	0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x5f, 0x44, 0x45, 0x52, 0x49, 0x56,
	0x53, 0x10, 0x08, 0x2a, 0x2e, 0x0a, 0x11, 0x43, 0x6c, 0x61, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x54, 0x5f, 0x49,
	0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x54, 0x5f, 0x41, 0x4c,
	0x6c, 0x10, 0x01, 0x2a, 0x54, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a,
	0x43, 0x4d, 0x54, 0x5f, 0x49, 0x47, 0x4e, 0x4f, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x4d, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4d,
	0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x55, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4d,
	0x54, 0x5f, 0x4b, 0x41, 0x54, 0x48, 0x45, 0x10, 0x03, 0x32, 0x48, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x13,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x49, 0x44, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x45, 0x72, 0x6e, 0x65, 0x73, 0x74, 0x6f, 0x47, 0x46, 0x2f, 0x62, 0x6f, 0x75, 0x6b,
	0x6b, 0x65, 0x72, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stories_proto_rawDescOnce sync.Once
	file_stories_proto_rawDescData = file_stories_proto_rawDesc
)

func file_stories_proto_rawDescGZIP() []byte {
	file_stories_proto_rawDescOnce.Do(func() {
		file_stories_proto_rawDescData = protoimpl.X.CompressGZIP(file_stories_proto_rawDescData)
	})
	return file_stories_proto_rawDescData
}

var file_stories_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_stories_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stories_proto_goTypes = []interface{}{
	(StatusType)(0),            // 0: stories.StatusType
	(ReactionType)(0),          // 1: stories.ReactionType
	(AudienceType)(0),          // 2: stories.AudienceType
	(CopyrigthType)(0),         // 3: stories.CopyrigthType
	(ClasificationType)(0),     // 4: stories.ClasificationType
	(CommentModerationType)(0), // 5: stories.CommentModerationType
	(*RequestWriteStory)(nil),  // 6: stories.RequestWriteStory
	(*ResponseID)(nil),         // 7: stories.ResponseID
	(*CategoryInfo)(nil),       // 8: stories.CategoryInfo
	(*LanguageInfo)(nil),       // 9: stories.LanguageInfo
	(*UserInfo)(nil),           // 10: stories.UserInfo
	(*TotalReactionInfo)(nil),  // 11: stories.TotalReactionInfo
	(*ChapterPosition)(nil),    // 12: stories.ChapterPosition
}
var file_stories_proto_depIdxs = []int32{
	0, // 0: stories.RequestWriteStory.Status:type_name -> stories.StatusType
	2, // 1: stories.RequestWriteStory.Audience:type_name -> stories.AudienceType
	3, // 2: stories.RequestWriteStory.Copyright:type_name -> stories.CopyrigthType
	4, // 3: stories.RequestWriteStory.Clasification:type_name -> stories.ClasificationType
	5, // 4: stories.RequestWriteStory.CommentModeration:type_name -> stories.CommentModerationType
	1, // 5: stories.TotalReactionInfo.Type:type_name -> stories.ReactionType
	6, // 6: stories.stories.WriteStory:input_type -> stories.RequestWriteStory
	7, // 7: stories.stories.WriteStory:output_type -> stories.ResponseID
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_stories_proto_init() }
func file_stories_proto_init() {
	if File_stories_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stories_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWriteStory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalReactionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stories_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChapterPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stories_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stories_proto_goTypes,
		DependencyIndexes: file_stories_proto_depIdxs,
		EnumInfos:         file_stories_proto_enumTypes,
		MessageInfos:      file_stories_proto_msgTypes,
	}.Build()
	File_stories_proto = out.File
	file_stories_proto_rawDesc = nil
	file_stories_proto_goTypes = nil
	file_stories_proto_depIdxs = nil
}
